name: build
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17]
    name: Build with Java ${{ matrix.java-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      # https://github.com/actions/setup-java
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn package
