name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java-version: 8
            path-sep: ":"
          - os: ubuntu-latest
            java-version: 11
            path-sep: ":"
          - os: ubuntu-latest
            java-version: 17
            path-sep: ":"
          - os: windows-latest
            java-version: 11
            path-sep: ";"
          - os: macos-latest
            java-version: 11
            path-sep: ":"
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} + Java ${{ matrix.java-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/actions/setup-java
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn package -DskipTests=true

      - name: Running tests
        run: mvn test

      - name: Running the example
        run: java -cp "./rust-maven-example/target/rust-maven-example-1.0.0-SNAPSHOT.jar${{ matrix.path-sep }}./jar-jni/target/jar-jni-1.0.0-SNAPSHOT.jar" io.questdb.example.rust.Main

