name: build
on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17]
    name: Linux + Java ${{ matrix.java-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/actions/setup-java
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: Run the example
        run: java -cp "./rust-maven-example/target/rust-maven-example-1.0.0-SNAPSHOT.jar:./jar-jni/target/jar-jni-1.0.0-SNAPSHOT.jar" io.questdb.rust.maven.example.Main
  windows:
    runs-on: windows-latest
    name: Windows + Java 11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: Run the example
        run: java -cp "./rust-maven-example/target/rust-maven-example-1.0.0-SNAPSHOT.jar;./jar-jni/target/jar-jni-1.0.0-SNAPSHOT.jar" io.questdb.rust.maven.example.Main
  mac:
    runs-on: macos-latest
    name: MacOS + Java 11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: Run the example
        run: java -cp "./rust-maven-example/target/rust-maven-example-1.0.0-SNAPSHOT.jar:./jar-jni/target/jar-jni-1.0.0-SNAPSHOT.jar" io.questdb.rust.maven.example.Main
  freebsd:
    runs-on: macos-12
    name: FreeBSD + Java 11
    steps:
    - uses: actions/checkout@v3
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg install -y curl
          pkg install -y openjdk[11]
          pkg install -y maven

        run: |
          freebsd-version
          pwd
          env
          ls -lah
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y', '--profile', 'minimal
          mvn package
          java -cp "./rust-maven-example/target/rust-maven-example-1.0.0-SNAPSHOT.jar:./jar-jni/target/jar-jni-1.0.0-SNAPSHOT.jar" io.questdb.rust.maven.example.Main
        
